[workspace]
resolver = "2"
members = [
    "shift",
    "tab-protocol",
    "tab-server",
    "tab-client",
]

[workspace.package]
edition = "2024"
version = "0.1.0-alpha"

[workspace.dependencies]
nix = { version = "0.29", default-features = false, features = ["socket", "uio"] }
base64 = "0.22"
uuid = { version = "1.10", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
easydrm = "0.3.0"
